name: Docker Pipeline

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Uploading HTML to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building the Docker Image:latest
        run: docker build -t iftikharmhd/docker-pipeline:latest .

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push iftikharmhd/docker-pipeline:latest
            